<?php
  function shift_cipher_menu() {
    $items['shift_cipher'] = array(
      'title' => 'Shift Cipher',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('form_input'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
    $items['shift_cipher_success_page'] = array(
      'title' => 'Encryption Result',
      'page callback' => 'result',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    return $items;
  }


//======================FORM INPUT =============================================
  function form_input() {
    $form['shift_value'] = array(
      '#title' => "Shift Value",
      '#type' => 'textfield',
      '#description' => t('Please enter the <strong>shift value</strong> for the encryption'),
      '#element_validate' => array('element_validate_integer_positive'),
      '#required' => TRUE,
    );
    $form['shift_direction'] = array(
      '#title' => "Shift Direction",
      '#type' => 'textfield',
      '#description' => t('Please enter the <strong>direction(left/right)</strong> of the desired shift'),
      '#element_validate' => array('element_validate_direction'),
      '#required' => TRUE,
    );
    $form['phrase'] = array(
      '#title' => "Phrase to be encrypted",
      '#type' => 'textfield',
      '#description' => t('Please enter the phraze you want to encrypt'),
      '#element_validate' => array('element_validate_phrase'),
      '#required' => TRUE,
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Encrypt',
    );
    return $form;
  }

  function form_input_submit($form, &$form_state) {
    $alphabet = array('a', 'b', 'c', 'd',	'e', 'f',	'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',	'u', 'v', 'w', 'x', 'y', 'z');
    $value = intval($form_state['values']['shift_value']); //string turns to number
    $direction = $form_state['values']['shift_direction'];
    $phrase = str_split(strtolower($form_state['values']['phrase']));


    for($p_index = 0; $p_index < count($phrase); $p_index++) {
      for($a_index = 0; $a_index < count($alphabet); $a_index++) {
        if($phrase[$p_index] == $alphabet[$a_index] && $direction == 'left') {
          $phrase[$p_index] = $alphabet[$a_index - $value];
        }elseif($phrase[$p_index] == $alphabet[$a_index] && $direction == 'right') {
          $phrase[$p_index] = $alphabet[$a_index += $value]; // + alone does not work!
        }
      }
    }

    $_SESSION['shift_cipher_output'] = implode($phrase);
    $form_state['redirect'] = 'shift_cipher_success_page';
  }

  function result() {
    $result = $_SESSION['shift_cipher_output'];
    return $result;
  }

  // echo '<pre>';
  // var_dump($result);
  // echo '</pre>';
  // exit;

  //======================ELEMENT VALIDATIONS=====================================
  function element_validate_direction($element) {
    $user_input_direction = strtolower($element['#value']);
    $acceptable_directions = array('left', 'right');
    if(!in_array($user_input_direction, $acceptable_directions)) {
      form_error($element, t('The direction needs to be either Left or Right.'));
    }
  }

  function element_validate_phrase($element) {
    $phrase_exploded = explode(" ", $element['#value']);
    foreach ($phrase_exploded as $word) {
      if(!ctype_alpha($word)) { // look into ctype_punct for punctuations
        form_error($element, t('The phrase needs to consist of letters and punctuations.'));
      }
    }
  }
